version: '1.2'

services:
  php-env:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 2137:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database:/home
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 7312:80
    environment:
      - PMA_ARBITRARY=1